// <auto-generated />
namespace Project4_CodeFirst_Movie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_Category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Category));
        
        string IMigrationMetadata.Id
        {
            get { return "202411281316057_add_Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
